// This file was generated by liblab | https://liblab.com/

import { TestSdk } from 'test-sdk';

(async () => {
  const testSdk = new TestSdk({
    token: 'YOUR_TOKEN',
  });

  const { data } = await testSdk.pets.listPets({
    limit: 81,
  });

  console.log(data);
})();
