// This file was generated by liblab | https://liblab.com/

import { PetstoreClient } from 'petstore_client';

(async () => {
  const petstoreClient = new PetstoreClient({
    token: 'YOUR_TOKEN',
  });

  const { data } = await petstoreClient.pets.listPets({
    limit: 81,
  });

  console.log(data);
})();
