// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const pet = z.lazy(() => {
  return z.object({
    id: z.number(),
    name: z.string(),
    tag: z.string().optional(),
  });
});

/**
 *
 * @typedef  {Pet} pet
 * @property {number}
 * @property {string}
 * @property {string}
 */
export type Pet = z.infer<typeof pet>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const petResponse = z.lazy(() => {
  return z
    .object({
      id: z.number(),
      name: z.string(),
      tag: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      tag: data['tag'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const petRequest = z.lazy(() => {
  return z
    .object({ id: z.number().nullish(), name: z.string().nullish(), tag: z.string().nullish() })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      tag: data['tag'],
    }));
});
